services:
  exigentdevdimapi:
    image: exigentdev/exigentdevdimapi:latest
    container_name: exigentdevdimapi
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3006:5190"
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_SIGNINGKEY=${JWT_SIGNINGKEY}
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5190/health"]
      interval: 30s
      timeout: 10s
      retries: 3
